services:
  relay:
    build:
      context: .
      dockerfile: src/dockerfile
    ports:
      - 8000:8000
    environment:
      KUBEFLOW_USERNAME: ${KUBEFLOW_USERNAME}
      KUBEFLOW_PASSWORD: ${KUBEFLOW_PASSWORD}
      KUBEFLOW_HOST: ${KUBEFLOW_HOST}
      LAKEFS_HOST: ${LAKEFS_HOST}
      LAKEFS_ID: ${LAKEFS_ID}
      LAKEFS_TOKEN: ${LAKEFS_TOKEN}
      PRODUCTION_MODE: prod
